### ISSUE TITLE
Use \r instead of \n

### ISSUE THREAD

**Issue by soundstorm** [konikvranik/pyCEC#70]
The default telnet implementation of HASS uses `\r` as line detection, I changed it on my pyCEC installations accordingly, as I like to control multiple instances via telnet instead of one via the `hdmi_cec`

**Comment by soundstorm** [comment]
Current switches config:
```
- platform: telnet
  switches:
    some_device_id:
      name: "Some Device Name"
      resource: xxx.xxx.xxx.xxx
      port: 9526
      command_on: '10:04'
      command_off: '10:36'
      command_state: '10:8f'
      value_template: '{{ value == "01:90:00" }}'
      timeout: 1
```
